### PR TITLE
Make cross contract communication work using ERC20 wrapper (Solidity)

### PR DESCRIPTION
**Pull request by ebma**
Note: This PR is implemented assuming the changes introduced by [this](https://github.com/pendulum-chain/pendulum/pull/248) PR.

This PR implements an ERC 20 wrapper contract in Solidity. The contract is able to directly call the chain extensions of our chain. With this implementation, we don't need to deploy a separate ink! wrapper contract since the on-chain data is provided here already. 

## Notes
The `abi.encode()/decode()` functions are able to scale encode/decode out-of-the-box. However we need to be careful when crafting the inputs the encoding function. For example, we now use the knowledge about the structure of our `CurrencyId` enum and build it manually. 

> Solang on the substrate target will use SCALE if you do abi.encode(), so this can be used. AFAIR the enum variants will just count up. For example CurrencyId::Native would be 0x00, CurrencyId::XCM(0) would be 0x0100 (variant following the data it's holding) [Cyrill, Parity]

## TODO 
- [x] Implement chain extension communication for all functions
- [x] Extend `createCurrencyId()` function to support Stellar assets. This might be a little trickier since the Stellar assets are nested in the `CurrencyId` enum. It might be a good idea to test how some Stellar currencies look `encode()`d  in Rust code and then try to rebuild that here.
- [ ] (Optional) Refactor `CurrencyId` encoding. Maybe move it to another file which could then also handle other SCALE encoding problems.

## Testing
From the root directory use the following commands to compile both contracts.
```
solang compile --target substrate --output target/solang/contracts erc20-wrapper/erc20-wrapper.sol
solang compile --target substrate --output target/solang/contracts solidity-sample/pool.sol --importmap @openzeppelin=solidity-sample/openzeppelin-contracts/
```

When deploying the erc20-wrapper contract in [contracts UI](https://contracts-ui.substrate.io/add-contract) make sure you connect to Foucoco (as it has the chain extension available). In the constructor, you can leave all values empty/default to test for the 'Native' currency. To deploy a wrapper for the `XCM(0)` currency, you would have to use `variant: 0` and `index: 0` when constructing the contract.

### CODE REVIEW

**Review by ashneverdawn — APPROVED** [review]
The user interface in contracts-ui is now ugly because values are now in bytes instead of enum. 
Making the constructor expect an enum and then making the conversion would most likely solve that. 
Could be done in this PR or a future PR, up to you. 
Other than that, this looks good to me 👍

**Comment by ebma** [comment]
> Making the constructor expect an enum and then making the conversion would most likely solve that.

True, it's less convenient to deploy now. But since it's most likely going to be us deploying it, I think it's okay if the developer experience is not ideal with the constructor. As far as I know, Solidity enums are less powerful compared to Rust enums, ie. they cannot be nested, which is why we can't rebuild that conveniently in Solidity.

**Comment by ashneverdawn** [comment]
> > Making the constructor expect an enum and then making the conversion would most likely solve that.
> 
> True, it's less convenient to deploy now. But since it's most likely going to be us deploying it, I think it's okay if the developer experience is not ideal with the constructor. As far as I know, Solidity enums are less powerful compared to Rust enums, ie. they cannot be nested, which is why we can't rebuild that conveniently in Solidity.

True, but if we could at least do something about the `code` and `issuer` because entering bytes12 and a bytes32 one byte at a time whenever we deploy the contract manually would be tedious. Maybe the constructor could take string? As is if they are really strings, otherwise hexadecimal. wdyt?

**Comment by ebma** [comment]
Good point. I'll try to figure that out.

**Review by TorstenStueber — APPROVED** [review]
Looks good!

**Comment by ebma** [comment]
@ashneverdawn I tried to make it work but gave up on it because it makes it really dirty as we need more checks and overall it doesn't really make sense to change it in the contract itself because the problem originates from the user interface of contracts UI. If you use polkadot.js to deploy the contract, it's all good and you can provide hex values which are more convenient. 

image

I will leave it as is.

**Pull request merged**
