### PR TITLE
Fix cross contract communication

### PR DESCRIPTION
**Pull request by ebma**
This draft PR is used for experimenting with problems about the cross-contract communication between solidity and ink!
It might never get merged but I opened it for collaboration purposes. 

## How to

To compile the test contract use
```
cd ink-test
cargo contract build
```

To compile the solidity contract use (from root directory)
```
solang compile --target substrate --output target/solang/contracts solidity-sample/erc20-test.sol --importmap @openzeppelin=solidity-sample/openzeppelin-contracts/

```

####  We need to SCALE encode the results before returning them to the calling Solidity contract. 

This way, we ensure that decoding works as expected. 
```
        #[ink(message, selector = 0x00000000)]
        pub fn foo(&self) -> ink::prelude::vec::Vec<u8> {
            use scale::Encode;
            **ink::prelude::string::String::new().encode()**
        }
```
This means that also for functions that return a balance type like `u256` we should instead change the return value to `Vec<u8>` and call `encode()` before returning the value.

On the Solidity side we can then decode with eg. 
```
        function caller(address ink) public {
                (bool success, bytes raw_data) = ink.call(hex"00000000");
                require(success);
                if (raw_data[0] == 0) { // Success case
                    /* will be 0 anyways but we can't just "skip" that | this will contain the contents of the "Vec<u8>" */
                    (uint8 result, bytes b) = abi.decode(raw_data, (uint8, bytes));
                    string s = abi.decode(b, string);
                        print(s);
                }
        }
```

### CODE REVIEW

**Comment by TorstenStueber** [comment]
But isn't this a big problem because now the Solidity code needs to be handcrafted to interact with ink! smart contracts?

The whole original idea and intention of this whole research project (the "0xAmber solution") was to find a way to compile the suite of Solidity smart contracts without touching their code.

Do I misunderstand this?

**Comment by ebma** [comment]
> But isn't this a big problem because now the Solidity code needs to be handcrafted to interact with ink! smart contracts?

Yes, that's very correct. The idea was to first figure out if/how it's possible to transfer data between ink!/solidity correctly and without any loss before figuring out how to deal with the IERC20 problem. Because if we don't know how this works in the first place, then we don't need to look into the interface problem.

It seems like we have two ways to solve the IERC-20 problem such that other Solidity projects don't have to change anything about their code. 
1. We have two wrapper contracts. Our existing ink! PSP-22 wrapper, that communicates with an IERC20-wrapper on Solidity which is able to decode and understand the values transferred by the PSP-22 wrapper. The 0xAmber project would then communicate with he IERC-20 wrapper since both are solidity contract and can communicate as is, without any encoding issues.
2. We remove our PSP-22 ink! wrapper and instead implement the chain extension functions that our PSP-22 ink! contract is using to communicate with our on-chain data directly into the new IERC-20 wrapper. The good thing is that solang by now supports calling chain extensions from within Solidity contracts, see [here](https://solang.readthedocs.io/en/latest/language/builtins.html#chain-extension-uint32-id-bytes-input-returns-uint32-bytes).

Since option 2) involves fewer contract calls, thus is more gas efficient, and since we would need to deploy fewer smart contracts overall, ie. we don't have to have our ink! wrapper, option 2) is preferable. However, at this very moment it might take more time to implement approach 2) over approach 1).

**Comment by TorstenStueber** [comment]
@ebma I strongly prefer 2 because 2 layer wrappers is very inefficient. However, at this point we should only do it if it takes at most two days to develop and properly test.

I think that ERC20 is a very simple interface that does not have a lot of functions so that it seems to be possible to me.

**Comment by ashneverdawn** [comment]
> @ebma I strongly prefer 2 because 2 layer wrappers is very inefficient. However, at this point we should only do it if it takes at most two days to develop and properly test.
> 
> I think that ERC20 is a very simple interface that does not have a lot of functions so that it seems to be possible to me.

I don't know about *very* inefficient, the solidity wrapper is pretty light and doesn't do anything other than calling the other contract. But yeah, I agree it's definitely not optimal.


But yeah, there is actually an option 3 which is to modify ink's codegen to allow the ink contract to satisfy IERC20, removing the need for the wrapper solidity contract. This has the advantage to be able to keep using our shared types with the chain extension, since both ink and substrate are in rust. 

In option 2, the downside we'd have to rewrite all the types including CurrencyId and keep maintaining them on both sides. We may also lose some debugging ability, as on the ink side there is a lot more tooling provided by parity, like errors, integration tests, macros, libraries, etc.

I favor option 3, which I think would actually be less work than option 2. I was already most of the way there, actually. I just needed to remove the first 2 bytes from the beginning of the data returned. The first one being the length and the second one being the Result<> container. We'd have to dig into the macros to remove those two bytes, and I though that might take some time to understand, so I came up with option 1 because of our time constraints. According to Cyrill, Parity is actually planning to provide the IERC20 compatible macros at some point, so maybe by the time we get to this, we won't actually have to dig into the macros and can just use the new ones.

But, either way, I think both option 2 and 3 will take more than 2 days, so we probably still need to focus on option 1 right now.

**Comment by ebma** [comment]
I agree that it would be ideal if we could have the wrapper written in ink! because it has the best tooling for us, ie. option 3) would be ideal. But I think we should wait for Parity to finish building the necessary code/macros we need. It's hard to tell how difficult this is and it might turn out to be very hacky if we try to do it. 

I don't think that maintaining the types in the Solidity wrapper for option 2) is problematic. It's actually just the `CurrencyId` type that we need to be careful with, the rest is simple. I already got all chain extension calls to work [here](https://github.com/pendulum-chain/pendulum-ink-wrapper/pull/16).

I think it doesn't make sense to go for option 1) since we seem to agree that it's the least efficient and least favorable option out of these three. We shouldn't spend money on auditing a solution that we know we can improve easily.

**Pull request closed without merging**
